name: FutureHolograms
version: 1.0.4.5
main: me.TheJokerDev.futureholograms.Main
api-version: 1.17
depend: [ PlaceholderAPI, HolographicDisplays ]
authors: [ TheJokerDev ]
description: Create custom holograms with uniques options.
website: https://github.com/TheJokerDev/FutureHolograms

commands:
  futureholograms:
    aliases: [fholo, fholograms, futureholo]
    description: Main command for the plugin.
